version: '2'
services:
    jhbase-app:
        image: jhbase
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://jhbase-mysql:3306/jhbase?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhbase-mysql:
        extends:
            file: mysql.yml
            service: jhbase-mysql
